#ifndef hwshader_OCL
#define hwshader_OCL
const char *hwshader_ocl =
"struct PixelElement{\n"
"    float dr, dg, db;\n"
"    float sr, sg, sb;\n"
"    float x, y, z;\n"
"    float nx, ny, nz;\n"
"    float roughness;\n"
"    float eta_r, eta_g, eta_b, k_r, k_g, k_b;\n"
"    float wi_x, wi_y, wi_z;\n"
"};\n"
"\n"
"struct LightElement{\n"
"    float r, g, b;\n"
"    float nx, ny, nz;\n"
"    float x, y, z;\n"
"    float rad;\n"
"    float coeff;\n"
"};\n"
"\n"
"struct OutputElement{\n"
"    float r, g, b;\n"
"};\n"
"\n"
"__kernel void shade(__global const struct PixelElement* A, __global const struct LightElement* B, \n"
"    __global struct OutputElement *C, int num_pixels){\n"
"    int i = get_global_id(0);\n"
"    if(i >= num_pixels){\n"
"        return;\n"
"    }\n"
"    \n"
"    C[i].r = A[i].dr;\n"
"    C[i].g = A[i].dg;\n"
"    C[i].b = A[i].db;\n"
"}\n";
#endif
